springdoc:
  swagger-ui:
    url: /openapi.yaml

spring:
  datasource:
    url: jdbc:h2:file:./data/sampledb;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: user
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID:}
            client-secret: ${GITHUB_CLIENT_SECRET:}
            scope: read:user, repo

token:
  github-pat: ${GITHUB_PAT:}
  backend-token: ${BACKEND_TOKEN:}
  frontend-token: ${FRONTEND_TOKEN:}
  sonar-token: ${SONAR_TOKEN:}

app:
  url: ${APP_URL:http://localhost:8080}
  github-url: 'https://api.github.com'
  github-owner: 'pjalbrz16'
  github-worker-repo: 'blade-runner-worker'
  sonar-component-key: 'pjalbrz16_github-worker-action'